version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "WeWillWin"
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  supplier-monitoring-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080 # Порт
      DB_URL: "jdbc:postgresql://postgres:5432/postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "WeWillWin"
    ports:
      - 8080:8080
